### ISSUE TITLE
Inquiry for performance results

### ISSUE THREAD

**Issue by ZekunStevenZhang** [Prinsphield/Adversarial_Reprogramming#1]
Thanks for sharing this code, i got a question for the performance. 

i tried to run ur main_single file and get a result of 80%. Were you using the same configuration to get 94% performance?

**Comment by Prinsphield** [comment]
Please try to run `main.py` even if you have one GPU card. It is easy to achieve 94%.

**Comment by ZekunStevenZhang** [comment]
yes thanks
